import { ProfileConfig, Domain } from '../types';

export const PROFILES: Record<Domain, ProfileConfig> = {
  GOV: {
    id: 'GOV',
    name: 'Государственная организация',
    description: 'Министерства, ведомства, госкомпании. Официальные письма, поручения, протоколы, строгий документооборот.',
    icon: '🏛️',
    labels: {
      tasks: 'Поручения',
      meetings: 'Заседания',
      reports: 'Сводки',
      letters: 'Письма',
      documents: 'Документооборот',
      team: 'Штат',
      journal: 'Журнал регистрации',
      ai: 'ИИ-Помощник',
      settings: 'Настройки',
      dashboard: 'Панель управления',
      new_task: 'Новое поручение',
      new_meeting: 'Новое заседание',
      new_report: 'Новая сводка',
    },
    modules: ['dashboard', 'tasks', 'meetings', 'reports', 'letters', 'documents', 'team', 'journal', 'ai', 'settings'],
    aiTone: 'Строго официальный, деловой, без разговорных выражений. Используй терминологию государственного делопроизводства (поручения, распоряжения, протоколы, согласования).',
    aiRules: [
      'Не выдумывай факты и цифры',
      'Проверяй формальность и деловой стиль',
      'Предупреждай о неполных данных',
      'Готовь письма в официально-деловом стиле',
      'Используй узбекский латинский при необходимости',
      'Фиксируй решения и создавай протоколы',
    ],
    requiredFields: {
      task: ['title', 'assignee', 'deadline', 'department'],
      meeting: ['title', 'date', 'participants', 'agenda'],
      letter: ['subject', 'recipient'],
    },
  },

  CEO: {
    id: 'CEO',
    name: 'Бизнес-ассистент CEO',
    description: 'Предприниматели, CEO, владельцы бизнеса. Задачи, встречи, контроль, быстрые брифинги.',
    icon: '💼',
    labels: {
      tasks: 'Задачи',
      meetings: 'Встречи',
      reports: 'Отчёты',
      letters: 'Письма',
      documents: 'Документы',
      team: 'Команда',
      journal: 'Реестр',
      ai: 'ИИ-Ассистент',
      settings: 'Настройки',
      dashboard: 'Главная',
      new_task: 'Новая задача',
      new_meeting: 'Новая встреча',
      new_report: 'Новый отчёт',
    },
    modules: ['dashboard', 'tasks', 'meetings', 'reports', 'letters', 'documents', 'team', 'journal', 'ai', 'settings'],
    aiTone: 'Профессионально, по-деловому, чётко и конкретно. Ориентация на результат и действия.',
    aiRules: [
      'Фокусируйся на результатах и KPI',
      'Предлагай следующие шаги',
      'Готовь ежедневные брифинги',
      'Помогай контролировать поручения',
      'Анализируй риски для бизнеса',
    ],
    requiredFields: {
      task: ['title', 'assignee', 'deadline'],
      meeting: ['title', 'date'],
      letter: ['subject'],
    },
  },

  IT: {
    id: 'IT',
    name: 'IT / Startup ассистент',
    description: 'IT-компании, стартапы, продуктовые команды. Спринты, таски, синки, roadmap.',
    icon: '💻',
    labels: {
      tasks: 'Таски / Спринты',
      meetings: 'Синки',
      reports: 'Метрики',
      letters: 'Коммуникации',
      documents: 'Документация',
      team: 'Команда',
      journal: 'Бэклог',
      ai: 'AI-Ассистент',
      settings: 'Settings',
      dashboard: 'Dashboard',
      new_task: 'Создать таск',
      new_meeting: 'Новый синк',
      new_report: 'Новая метрика',
    },
    modules: ['dashboard', 'tasks', 'meetings', 'reports', 'documents', 'team', 'journal', 'ai', 'settings'],
    aiTone: 'Современно, коротко, по-agile. Используй технические термины (блокеры, спринты, релизы, action items). Можно использовать англицизмы.',
    aiRules: [
      'Резюмируй технические обсуждения',
      'Выделяй blockers и action items',
      'Готовь status update',
      'Помогай с проектными отчётами',
      'Оценивай приоритеты задач',
    ],
    requiredFields: {
      task: ['title', 'priority'],
      meeting: ['title'],
      letter: ['subject'],
    },
  },

  PRIVATE: {
    id: 'PRIVATE',
    name: 'Личный / Family ассистент',
    description: 'Личные помощники, family office, lifestyle management. Поездки, покупки, напоминания.',
    icon: '🏠',
    labels: {
      tasks: 'Поручения',
      meetings: 'Встречи',
      reports: 'Заметки',
      letters: 'Сообщения',
      documents: 'Файлы',
      team: 'Контакты',
      journal: 'Дневник',
      ai: 'Помощник',
      settings: 'Настройки',
      dashboard: 'Главная',
      new_task: 'Новое поручение',
      new_meeting: 'Новая встреча',
      new_report: 'Новая заметка',
    },
    modules: ['dashboard', 'tasks', 'meetings', 'documents', 'team', 'ai', 'settings'],
    aiTone: 'Максимально практично и дружелюбно. Меньше официальности, больше чек-листов и коротких списков.',
    aiRules: [
      'Помогай планировать',
      'Делай списки и чек-листы',
      'Напоминай о важных делах',
      'Структурируй бытовые и деловые задачи',
      'Будь конфиденциальным',
    ],
    requiredFields: {
      task: ['title'],
      meeting: ['title'],
    },
  },

  OPS: {
    id: 'OPS',
    name: 'Операционный ассистент',
    description: 'Управление процессами, контроль отделов, регламенты, подрядчики, показатели.',
    icon: '⚙️',
    labels: {
      tasks: 'Задачи',
      meetings: 'Совещания',
      reports: 'Отчёты',
      letters: 'Переписка',
      documents: 'Регламенты',
      team: 'Отделы',
      journal: 'Контроль',
      ai: 'ИИ-Аналитик',
      settings: 'Настройки',
      dashboard: 'Контрольная панель',
      new_task: 'Новая задача',
      new_meeting: 'Новое совещание',
      new_report: 'Новый отчёт',
    },
    modules: ['dashboard', 'tasks', 'meetings', 'reports', 'documents', 'team', 'journal', 'ai', 'settings'],
    aiTone: 'Чёткий, аналитический, ориентированный на процессы и показатели. Выделяй задержки и узкие места.',
    aiRules: [
      'Контролируй процессы и сроки',
      'Выявляй узкие места',
      'Анализируй показатели отделов',
      'Помогай с жалобами и улучшениями',
      'Следи за повторяющимися проблемами',
    ],
    requiredFields: {
      task: ['title', 'assignee', 'department', 'deadline'],
      meeting: ['title', 'date', 'agenda'],
      letter: ['subject', 'recipient'],
    },
  },

  PROJECT: {
    id: 'PROJECT',
    name: 'Проектный ассистент',
    description: 'Проектные команды, консалтинг, внедрения. Этапы, сроки, ответственные, статусы.',
    icon: '📊',
    labels: {
      tasks: 'Задачи проекта',
      meetings: 'Встречи',
      reports: 'Статус-отчёты',
      letters: 'Коммуникации',
      documents: 'Документация проекта',
      team: 'Команда проекта',
      journal: 'Риски и решения',
      ai: 'ИИ-Аналитик',
      settings: 'Настройки',
      dashboard: 'Обзор проекта',
      new_task: 'Новая задача',
      new_meeting: 'Новая встреча',
      new_report: 'Новый статус',
    },
    modules: ['dashboard', 'tasks', 'meetings', 'reports', 'documents', 'team', 'journal', 'ai', 'settings'],
    aiTone: 'Структурированно, по-проектному. Фокус на сроках, рисках, статусах. Используй project management терминологию.',
    aiRules: [
      'Контролируй сроки и этапы',
      'Выделяй риски',
      'Готовь статус для руководителя',
      'Фиксируй решения',
      'Помогай с проектной документацией',
    ],
    requiredFields: {
      task: ['title', 'assignee', 'deadline'],
      meeting: ['title', 'date', 'participants'],
      letter: ['subject'],
    },
  },
};

export const ALL_PROFILE_IDS: Domain[] = ['GOV', 'CEO', 'IT', 'PRIVATE', 'OPS', 'PROJECT'];

export const getProfile = (id: Domain): ProfileConfig => {
  return PROFILES[id] || PROFILES.CEO;
};
